export const reviewMocks = [
  {
    id: "6iaV-jUSjfl-gGk8EOdQ1",
    name: "Андрей",
    text: "Фильм хороший, но сюжет немного затянут",
    rating: 7,
  },
  {
    id: "-b9ezNy3oSoMpldgUl_IC",
    name: "Екатерина",
    text: "В целом, фильм понравился, но некоторые моменты были не очень понятны",
    rating: 6,
  },
  {
    id: "joAPS_G2-BgIIYQNmkWHh",
    name: "Сергей",
    text: "Мне не очень понравился фильм, но в нем есть несколько интересных моментов",
    rating: 5,
  },
  {
    id: "un6oKnwU6pSZaxFfWQdUS",
    name: "Ольга",
    text: "Это был интересный опыт, но я ожидала большего",
    rating: 4,
  },
  {
    id: "F_sUc0y7PUNvm0_FVgK-l",
    name: "Анна",
    text: "Очень хороший фильм, рекомендую всем посмотреть",
    rating: 9,
  },
  {
    id: "t8QHNLoec1QF1XFyObGk7",
    name: "Александр",
    text: "Этот фильм стоит посмотреть хотя бы ради актерского состава",
    rating: 8,
  },
  {
    id: "wkitGBsyiLgdasQ7FT4ca",
    name: "Елена",
    text: "Фильм оставляет после себя приятное впечатление, но можно было сделать его более захватывающим",
    rating: 7,
  },
  {
    id: "M0bg9QY5gVtupNaglrmua",
    name: "Роман",
    text: "Сюжет интересен, но финал мог быть более неожиданным",
    rating: 6,
  },
  {
    id: "sFpB1zc2RB1_06S9PMWj4",
    name: "Шутник",
    text: "Этот фильм - настоящий шедевр!",
    rating: 10,
  },
  {
    id: "oiwpcrBQAKj5K7smP3lVy",
    name: "Комик",
    text: "Не понимаю, что все так восхищаются этим фильмом",
    rating: 6,
  },
  {
    id: "OJwAR3gCG2uM2BuoKiJF-",
    name: "Приколист",
    text: "Пойду посмотрю что-нибудь другое, этот фильм не очень",
    rating: 2,
  },
  {
    id: "jDMdBarsmE6m7m0baXY4_",
    name: "Юморист",
    text: "Я не понимаю, как можно ставить такие низкие оценки",
    rating: 8,
  },
  {
    id: "OVPbCJzb8wOGfhJ54JbVc",
    name: "Хохмач",
    text: "Это самый смешной фильм, который я когда-либо видел",
    rating: 9,
  },
  {
    id: "OX0AuLOo8FQgK7thnTu5N",
    name: "Смех да и только",
    text: "Фильм просто смешной, но не более того",
    rating: 5,
  },
  {
    id: "wax4rsvm_h6UGqQwapz5j",
    name: "Хиханьки",
    text: "Очень смешно, но непонятно, что смешного",
    rating: 3,
  },
  {
    id: "FpeVYlPOHz4zbS4OQj5Dv",
    name: "Ха-ха",
    text: "Мне не смешно, но я улыбаюсь",
    rating: 7,
  },
  {
    id: "w32kK5oV6UIr1ZHdkkMAn",
    name: "Смешинка",
    text: "Ну очень смешно, чуть не лопнул со смеху",
    rating: 4,
  },
  {
    id: "JI5iDqk-wjl7HSYVCOZeW",
    name: "Андрей",
    text: "Фильм хороший, но сюжет немного затянут",
    rating: 7,
  },
  {
    id: "Yj8yaD05nzHMvQk0921xF",
    name: "Екатерина",
    text: "В целом, фильм понравился, но некоторые моменты были не очень понятны",
    rating: 6,
  },
  {
    id: "KCvD5gFmTn8NeK43QglKe",
    name: "Сергей",
    text: "Мне не очень понравился фильм, но в нем есть несколько интересных моментов",
    rating: 5,
  },
  {
    id: "PnxKfx6XS_RqcIxC7w4a7",
    name: "Ольга",
    text: "Это был интересный опыт, но я ожидала большего",
    rating: 4,
  },
  {
    id: "OGNSCmINS-MLVuuvhrtGh",
    name: "Анна",
    text: "Очень хороший фильм, рекомендую всем посмотреть",
    rating: 9,
  },
  {
    id: "LLcQ8y3uJHfl3bDeTWqea",
    name: "Александр",
    text: "Этот фильм стоит посмотреть хотя бы ради актерского состава",
    rating: 8,
  },
  {
    id: "Sx2k0OsFL0qot9r_twc9f",
    name: "Елена",
    text: "Фильм оставляет после себя приятное впечатление, но можно было сделать его более захватывающим",
    rating: 7,
  },
  {
    id: "xsZN4Nd8wOWxX5dEok7hM",
    name: "Роман",
    text: "Сюжет интересен, но финал мог быть более неожиданным",
    rating: 6,
  },
  {
    id: "Y16csQhvXC2VRZXiqwjWE",
    name: "Шутник",
    text: "Этот фильм - настоящий шедевр!",
    rating: 10,
  },
  {
    id: "zb3Ui_Hmmy83OsUcS8y7W",
    name: "Комик",
    text: "Не понимаю, что все так восхищаются этим фильмом",
    rating: 6,
  },
  {
    id: "yvLjlSo9w6T4Mp6gG22pc",
    name: "Приколист",
    text: "Пойду посмотрю что-нибудь другое, этот фильм не очень",
    rating: 2,
  },
  {
    id: "3U5SB0Bu8ysjvduFnAMZN",
    name: "Юморист",
    text: "Я не понимаю, как можно ставить такие низкие оценки",
    rating: 8,
  },
  {
    id: "-5WByyVj9Oc_3RLZ_-jv5",
    name: "Хохмач",
    text: "Это самый смешной фильм, который я когда-либо видел",
    rating: 9,
  },
  {
    id: "Ryx3f_0VKXgb4qKbEYRqT",
    name: "Смех да и только",
    text: "Фильм просто смешной, но не более того",
    rating: 5,
  },
  {
    id: "qAwLtajTlVz6Y-0OGbjiP",
    name: "Хиханьки",
    text: "Очень смешно, но непонятно, что смешного",
    rating: 3,
  },
  {
    id: "9wUCPgqmjqLOc0g-80Ioj",
    name: "Ха-ха",
    text: "Мне не смешно, но я улыбаюсь",
    rating: 7,
  },
  {
    id: "0VioUEGFNySTyrRDEKRlj",
    name: "Смешинка",
    text: "Ну очень смешно, чуть не лопнул со смеху",
    rating: 4,
  },
];